In [ ]:
# /rds/general/user/yl9422/home/files/M4R-Elly/StatQA/Data/Integrated Dataset/Balanced Benchmark/StatQA.csv
# /rds/general/user/yl9422/home/files/M4R-Elly/StatQA/Data/Integrated Dataset/Dataset with Prompt/Test Set/mini-StatQA for zero-shot.csv


import pandas as pd
statqa_df = pd.read_csv('/rds/general/user/yl9422/home/files/M4R-Elly/StatQA/Data/Integrated Dataset/Balanced Benchmark/StatQA.csv')
mini_statqa_df = pd.read_csv('/rds/general/user/yl9422/home/files/M4R-Elly/StatQA/Data/Integrated Dataset/Dataset with Prompt/Test Set/mini-StatQA for zero-shot.csv')

In [ ]:
statqa_df_duplicates = statqa_df[statqa_df['refined_question'].duplicated(keep=False)]
statqa_df_duplicates

,dataset,refined_question,relevant_column,results,ground_truth,task,difficulty,id
1263,US Christmas Tree Sales Dataset,How strong is the link between the average cos...,"[{""column_header"": ""Average Tree Price"", ""is_s...","[{""method"": ""Kendall Correlation Coefficient"",...","{""columns"": [""Average Tree Price"", ""Sales""], ""...",Correlation Analysis,hard,1264
1265,US Christmas Tree Sales Dataset,How strong is the relationship between the ave...,"[{""column_header"": ""Average Tree Price"", ""is_s...","[{""method"": ""Kendall Correlation Coefficient"",...","{""columns"": [""Average Tree Price"", ""Sales""], ""...",Correlation Analysis,hard,1266
1266,US Christmas Tree Sales Dataset,How strong is the relationship between the ave...,"[{""column_header"": ""Average Tree Price"", ""is_s...","[{""method"": ""Kendall Correlation Coefficient"",...","{""columns"": [""Average Tree Price"", ""Sales""], ""...",Correlation Analysis,hard,1267
1267,US Christmas Tree Sales Dataset,How strong is the relationship between the ave...,"[{""column_header"": ""Average Tree Price"", ""is_s...","[{""method"": ""Kendall Correlation Coefficient"",...","{""columns"": [""Average Tree Price"", ""Sales""], ""...",Correlation Analysis,hard,1268
1272,US Christmas Tree Sales Dataset,How strong is the link between the mean cost o...,"[{""column_header"": ""Average Tree Price"", ""is_s...","[{""method"": ""Kendall Correlation Coefficient"",...","{""columns"": [""Average Tree Price"", ""Sales""], ""...",Correlation Analysis,hard,1273
...,...,...,...,...,...,...,...,...
11516,Bank Customer Churn Prediction Dataset,Do the CreditScore and NumOfProducts exhibit s...,"[{""column_header"": ""CreditScore"", ""is_strata"":...","[{""method"": ""Mood Variance Test"", ""result"": ""{...","{""columns"": [""CreditScore"", ""NumOfProducts""], ...",Variance Test,hard,11517
11527,Obesity or CVD Risk Dataset,Is there a statistically significant differenc...,"[{""column_header"": ""Age"", ""is_strata"": false, ...","[{""method"": ""Mood Variance Test"", ""result"": ""{...","{""columns"": [""Age"", ""Weight""], ""methods"": [""Mo...",Variance Test,hard,11528
11541,Exercise and Fitness Metrics Dataset,Do Heart Rate and BMI exhibit similar levels o...,"[{""column_header"": ""Heart Rate"", ""is_strata"": ...","[{""method"": ""Mood Variance Test"", ""result"": ""{...","{""columns"": [""Heart Rate"", ""BMI""], ""methods"": ...",Variance Test,hard,11542
11591,Pokedex Dataset,"Do the variables ""Total"" and ""Defense"" exhibit...","[{""column_header"": ""Total"", ""is_strata"": false...","[{""method"": ""Mood Variance Test"", ""result"": ""{...","{""columns"": [""Total"", ""Defense""], ""methods"": [...",Variance Test,hard,11592
11596,FIFA Official Dataset 2023,Is there uniformity in the variance of players...,"[{""column_header"": ""Overall"", ""is_strata"": fal...","[{""method"": ""Mood Variance Test"", ""result"": ""{...","{""columns"": [""Overall"", ""Height""], ""methods"": ...",Variance Test,hard,11597

In [5]:
mini_statqa_df_duplicates = mini_statqa_df[mini_statqa_df['refined_question'].duplicated(keep=False)]
mini_statqa_df_duplicates

,dataset,refined_question,relevant_column,task,difficulty,results,prompt
137,US Christmas Tree Sales Dataset,Does a linear relationship exist between the m...,"[{""column_header"": ""Average Tree Price"", ""is_s...",Correlation Analysis,medium,"[{""method"": ""Pearson Correlation Coefficient"",...",### Task Description: You need to select relev...
197,US Christmas Tree Sales Dataset,What is the strength of the correlation betwee...,"[{""column_header"": ""Number of trees sold"", ""is...",Correlation Analysis,medium,"[{""method"": ""Pearson Correlation Coefficient"",...",### Task Description: You need to select relev...
204,US Christmas Tree Sales Dataset,What is the correlation between the trend in t...,"[{""column_header"": ""Number of trees sold"", ""is...",Correlation Analysis,medium,"[{""method"": ""Pearson Correlation Coefficient"",...",### Task Description: You need to select relev...
273,US Christmas Tree Sales Dataset,How strong is the relationship between the num...,"[{""column_header"": ""Number of trees sold"", ""is...",Correlation Analysis,medium,"[{""method"": ""Pearson Correlation Coefficient"",...",### Task Description: You need to select relev...
428,Student Performance Prediction Dataset,Is there a similarity in the variability of fr...,"[{""column_header"": ""freetime"", ""is_strata"": fa...",Variance Test,medium,"[{""method"": ""Mood Variance Test"", ""result"": ""{...",### Task Description: You need to select relev...
488,US Christmas Tree Sales Dataset,What is the strength of the correlation betwee...,"[{""column_header"": ""Number of trees sold"", ""is...",Correlation Analysis,medium,"[{""method"": ""Pearson Correlation Coefficient"",...",### Task Description: You need to select relev...
765,Student Performance Prediction Dataset,Is there a similarity in the variability of fr...,"[{""column_header"": ""freetime"", ""is_strata"": fa...",Variance Test,medium,"[{""method"": ""Mood Variance Test"", ""result"": ""{...",### Task Description: You need to select relev...
798,US Christmas Tree Sales Dataset,Does a linear relationship exist between the m...,"[{""column_header"": ""Average Tree Price"", ""is_s...",Correlation Analysis,medium,"[{""method"": ""Pearson Correlation Coefficient"",...",### Task Description: You need to select relev...
939,US Christmas Tree Sales Dataset,How strong is the relationship between the num...,"[{""column_header"": ""Number of trees sold"", ""is...",Correlation Analysis,medium,"[{""method"": ""Pearson Correlation Coefficient"",...",### Task Description: You need to select relev...
1159,US Christmas Tree Sales Dataset,What is the correlation between the trend in t...,"[{""column_header"": ""Number of trees sold"", ""is...",Correlation Analysis,medium,"[{""method"": ""Pearson Correlation Coefficient"",...",### Task Description: You need to select relev...